# Use an official Python runtime as a base image
FROM python:3.8-slim-buster

# Install the necessary packages
RUN pip install --no-cache-dir \
    qiskit-terra==0.22.2 \
    qiskit-aer==0.11.1 \
    qiskit-machine-learning==0.6.0 \